[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcd = "2.3.0"
itertools = "0.10.5"
maplit = "1.0.2"
num = "0.4.1"
serde = "1.0.152"
serde_json = "1.0.91"
